version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "dependabot-updates"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "dependabot-updates"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
