REDIS_VARIANT = "redis"
FAKEREDIS_VARIANT = "fakeredis"

REMOVE_RANGE_SCRIPT_NAME = "remove_range"
NUM_MUL_SCRIPT_NAME = "num_mul"
NUM_FLOORDIV_SCRIPT_NAME = "num_floordiv"
NUM_MOD_SCRIPT_NAME = "num_mod"
NUM_POW_SCRIPT_NAME = "num_pow"
NUM_POW_FLOAT_SCRIPT_NAME = "num_pow_float"
NUM_TRUEDIV_SCRIPT_NAME = "num_truediv"
STR_APPEND_SCRIPT_NAME = "str_append"
STR_MUL_SCRIPT_NAME = "str_mul"
DATETIME_ADD_SCRIPT_NAME = "datetime_add"
DICT_POP_SCRIPT_NAME = "dict_pop"
DICT_POPITEM_SCRIPT_NAME = "dict_popitem"
