name: CodSpeed Benchmarks

on:
  push:
    branches:
      - main
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  mirror-redis:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    outputs:
      image: ${{ steps.mirror.outputs.image }}
    steps:
    - uses: actions/checkout@v5
    - id: mirror
      uses: ./.github/actions/mirror-redis
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

  benchmarks:
    needs: [mirror-redis]
    permissions:
      contents: read
      id-token: write
      packages: read
    environment:
      name: benchmark
    name: Run benchmarks
    runs-on: codspeed-macro
    services:
      redis:
        image: ${{ needs.mirror-redis.outputs.image }}
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        ports:
          - 6370:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: pyproject.toml
      - name: Install dependencies
        run: uv sync --locked --group benchmark
      - name: Run the benchmarks
        uses: CodSpeedHQ/action@v4
        with:
          mode: walltime
          token: ${{ secrets.CODSPEED_TOKEN }}
          run: uv run pytest benchmarks/ --codspeed
        env:
          REDIS_DB: 0
